# Generated by Django 4.2 on 2025-06-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='host',
            field=models.CharField(blank=True, help_text='Host:puerto para conexión gRPC (ej: localhost:50051)', max_length=200, null=True),
        ),
    ]
