# Generated by Django 4.1.13 on 2025-05-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_carritocompra_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritocompra',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carritocompra',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carritocompra',
            name='token_ws',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='carritocompra',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='carritocompra',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
