# Generated by Django 4.2 on 2025-06-24 03:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_sucursal_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, help_text='Stock disponible en la matriz'),
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bajo', 'Stock Bajo'), ('agotado', 'Stock Agotado'), ('critico', 'Stock Crítico')], default='bajo', max_length=20)),
                ('mensaje', models.TextField()),
                ('stock_actual', models.IntegerField()),
                ('umbral', models.IntegerField(default=5, help_text='Umbral para considerar stock bajo')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_resuelta', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='productos.producto')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.sucursal')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
