# Generated by Django 4.2 on 2025-06-24 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_stock_alertastock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.sucursal'),
        ),
    ]
