# Generated by Django 4.2 on 2025-06-24 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_venta_sucursal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='alertastock',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='es_casa_matriz',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='alertastock',
            name='sucursal_nombre',
            field=models.CharField(blank=True, help_text='Nombre de la sucursal gRPC (opcional)', max_length=100),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio al momento de agregar al carrito', max_digits=10),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Producto local', null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='producto_id_remoto',
            field=models.IntegerField(blank=True, help_text='ID del producto en servidor gRPC', null=True),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='sucursal_id_remoto',
            field=models.IntegerField(blank=True, help_text='ID de la sucursal gRPC', null=True),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='sucursal_nombre',
            field=models.CharField(blank=True, help_text='Nombre de la sucursal gRPC', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='es_local',
            field=models.BooleanField(default=True, help_text='True si es venta local, False si es de gRPC'),
        ),
        migrations.AddField(
            model_name='venta',
            name='sucursal_nombre',
            field=models.CharField(blank=True, help_text='Nombre de la sucursal gRPC (si no es local)', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together={('carrito', 'producto', 'producto_id_remoto', 'sucursal_id_remoto')},
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
