# Generated by Django 4.2 on 2025-06-24 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_itemcarrito_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='producto_categoria_remoto',
            field=models.CharField(blank=True, help_text='Categoría del producto remoto', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='producto_descripcion_remoto',
            field=models.TextField(blank=True, help_text='Descripción del producto remoto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='producto_id_remoto',
            field=models.IntegerField(blank=True, help_text='ID del producto en servidor gRPC', null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='producto_nombre_remoto',
            field=models.CharField(blank=True, help_text='Nombre del producto remoto', max_length=200),
        ),
        migrations.AlterField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
