# Generated by Django 4.2 on 2025-06-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_venta_producto_categoria_remoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertastock',
            name='sucursal_nombre',
            field=models.CharField(blank=True, help_text='Nombre de la sucursal gRPC (opcional)', max_length=100, null=True),
        ),
    ]
